create-bitcoin-conf:
  mkdir -p data/bitcoin && echo "regtest=1\n[regtest]\n txindex=1\nserver=1\nrpcuser=mempool\nrpcpassword=mempool\nrpcallowip=0/0\nrpcbind=0.0.0.0\nrpcport=18443\n" > data/bitcoin/bitcoin.conf
  echo "mempool:mempool" > data/bitcoin.cookie # needed for electrs

add-hosts:
  echo "127.0.0.1 mempool.ordim.local" | sudo tee -a /etc/hosts
  echo "127.0.0.1 ord.ordim.local" | sudo tee -a /etc/hosts
  echo "127.0.0.1 python.ordim.local" | sudo tee -a /etc/hosts

# docker-compose up

miner-create:
  docker-compose exec bitcoin-core bitcoin-cli -regtest createwallet miner

miner-load:
  docker-compose exec bitcoin-core bitcoin-cli -regtest loadwallet miner

e: # enter
 docker-compose exec bitcoin-core bash

generate-100:
  docker-compose exec bitcoin-core bitcoin-cli -regtest -generate 100

g: # generate
  docker-compose exec bitcoin-core bitcoin-cli -regtest -generate 1

faucet:
  docker-compose exec bitcoin-core bitcoin-cli -regtest \
    -rpcwallet=miner -named sendtoaddress \
      address=`docker-compose exec bitcoin-core bitcoin-cli -regtest getnewaddress` \
      amount=10 \
      fee_rate=1.1

